### ISSUE TITLE
The following packages must be added.

### ISSUE THREAD

**Issue by dayeondev** [OkDoky/moro_server_test#1]
모든 서버에서 그런 것은 아니겠지만 ubuntu 18.04에서 빌드 시, 패키지 부족을 겪었습니다. 
현재의 구조를 가져간다면, 몇 가지 패키지를 sh에 추가하는 것이 좋겠습니다.
```bash
* apt-get install ros-melodic-rosbridge-server
* apt-get install ros-melodic-map-server
* apt-get install ros-melodic-cv-bridge
```
### 과정
1. docker run / exec 후 roslaunch에서 에러 발생.
2. install.sh 재실행. 그러나, rosbridge_server 패키지 부재로 중단 됨.
3. ros-melodic-rosbridge-server 설치.
4. install.sh 재실행. 그러나, map_server 패키지 부재로 중단 됨.
5.  ros-melodic-map-server 설치.
6. install.sh 재실행. cv_bride 모듈 부재로 에러가 traceback 됨.
7. ros-melodic-cv-bridge 설치.
8. 정상적으로 동작함.

**Comment by OkDoky** [comment]
``` cd ~/catkin_ws && rosdep install -y -r --from-paths src --ignore-src```
라는 명령어가 install.sh에 들어있어 해당 패키지는 자동으로 설치되도록하였습니다.

해당 의존성 파일은 package.xml에 설정이 되어 있기에 따로 설치 명령어를 적어두지 않았습니다.
```
  <build_depend>rosbridge_server</build_depend>
  <build_depend>map_server</build_depend>
  <build_depend>cv_bridge</build_depend>
``` package.xml

**Comment by OkDoky** [comment]
#2 로 solve하였습니다.
